site_name: Global AI Standards (GAS)
site_description: "Single source of truth for GAS AI standards, governance, and compliance."

repo_url: https://github.com/NooMinds/global-ai-standards
# Docs live in a subfolder of the repo, so point GitHub's editor to that path:
edit_uri: edit/main/initial-standards-site/docs/

nav:
  - Home: index.md
  - Standards: standards.md
  - Compliance Quick-Guide: compliance.md
  - Templates: templates.md
  - Contribute: contribute.md

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - search.suggest
    - search.highlight
    - toc.integrate
    - content.action.edit   # shows the pencil "Edit this page"
    - content.action.view   # shows "View source"
  palette:
    - scheme: default
      primary: indigo
      accent: cyan
  icon:
    logo: material/robot-outline
    repo: fontawesome/brands/github

plugins:
  - search
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.frontmatter
  - meta
  - pymdownx.snippets

docs_dir: docs
extra_javascript:
  - assets/edit-this-page.js
