site_name: Global AI Standards
site_description: "Single source of truth for GAS AI standards, governance, and compliance."

repo_url: https://github.com/NooMinds/global-ai-standards
edit_uri: edit/main/initial-standards-site/docs/

nav:
  - Home: index.md

  - Global AI Child Safety:
      - Overview: child-safety.md

  - Global AI Personal Standard:
      - Overview: personal-standard.md

  - Global AI Business Standards:
      - Overview: business-standards.md
      - Compliance Quick-Guide: compliance.md

  - Global AI Business Enterprise:
      - Overview: business-enterprise.md
      - Compliance Quick-Guide: compliance.md
      
  - Global AI Custom Consultation: custom-instructions.md

  - Global AI Subject Instruction Packs: subject-instructions.md

  

- Global AI Custom Consultation:
    - Overview: custom-instructions.md
- Global AI Subject Instruction Packs:
    - Overview: subject-instructions.md




theme:
  name: material
  language: en
  features:
    - content.action.edit   # pencil: Edit this page
    - content.action.view   # View source
    - navigation.instant
    - search.suggest
    - search.highlight
    - toc.integrate
theme:
  name: material
  language: en
  features:
    - navigation.expand      # open all sections by default
    - navigation.sections    # show section headings as groups
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
    - toc.integrate
theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: indigo      # nav + accents
      accent: emerald      # buttons/pills
  features:
    - navigation.expand
    - navigation.sections
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
    - toc.integrate

extra_css:
  - styles/overrides.css


plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
docs_dir: docs

