site_name: Global AI Standards (GAS)
site_description: "Single source of truth for GAS AI standards, governance, and compliance."

nav:
  - Home: index.md
  - Standards: standards.md
  - Compliance Quick-Guide: compliance.md
  - Templates: templates.md
  - Contribute: contribute.md

    
theme:
  name: material
  language: en
  features:
    - navigation.instant
    - content.code.copy
    - search.suggest
    - search.highlight
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: cyan

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.frontmatter   # support YAML front matter (---)
  - meta                   # expose page metadata
  - pymdownx.snippets      # (optional) enable reusable includes


docs_dir: docs
