site_name: Global AI Standards (GAS)
site_description: "Single source of truth for GAS AI standards, governance, and compliance."

repo_url: https://github.com/NooMinds/global-ai-standards
edit_uri: edit/main/initial-standards-site/docs/

nav:
  - Home: index.md
  - Standards: standards.md
  - Compliance Quick-Guide: compliance.md
  - Templates: templates.md
  - Contribute: contribute.md

theme:
  name: material
  language: en

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
docs_dir: docs

