site_name: Global AI Standards
site_description: "Single source of truth for GAS AI standards, governance, and compliance."

repo_url: https://github.com/NooMinds/global-ai-standards
edit_uri: edit/main/initial-standards-site/docs/

nav:
  - Home: index.md
  - Global AI Child Safety: child-safety.md
  - Global AI Personal Standard: personal-standard.md
  - Global AI Business Standards:
      - Overview: business-standards.md
      - Compliance Quick-Guide: compliance.md
      - Custom Instructions: custom-instructions.md
      - Subject Instructions: subject-instructions.md
  - Global AI Business Enterprise Standard: business-enterprise.md
  - Reference (optional):
      - Standards Overview: standards.md
      - Model Development: standards/model-development.md
      - Data Governance: standards/data-governance.md
      - "MLOps & Release": standards/mlops-release.md
      - Evaluation & Monitoring: standards/evaluation-monitoring.md

theme:
  name: material
  language: en
  features:
    - content.action.edit   # pencil: Edit this page
    - content.action.view   # View source
    - navigation.instant
    - search.suggest
    - search.highlight
    - toc.integrate
theme:
  name: material
  language: en
  features:
    - navigation.expand      # open all sections by default
    - navigation.sections    # show section headings as groups
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
    - toc.integrate


plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
docs_dir: docs

