site_name: Global AI Standards
site_description: Exam-backed instructions to make AI accurate, compliant, and safe
site_author: Global AI Standards

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: indigo        # nav + accents
      accent: emerald        # buttons/pills
  features:
    - navigation.expand      # open sections by default
    - navigation.sections    # show section headings as groups
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
    - toc.integrate

extra_css:
  - styles/overrides.css

nav:
  - Home: index.md

  - Global AI Child Safety:
      - Overview: child-safety.md

  - Global AI Personal Standard:
      - Overview: personal-standard.md

  - Global AI Business Standards:
      - Business Standards Overview: business-standards.md
      - Compliance Quick-Guide: compliance.md

  - Global AI Business Enterprise:
      - Overview: business-enterprise.md
      - Compliance Quick-Guide: compliance.md

  - Global AI Custom Consultation:
      - Overview: custom-instructions.md

  - Global AI Subject Instruction Packs:
      - Overview: subject-instructions.md

  - What we did at Global AI Standards: standards/what-we-did.md
  - What you can do with Global AI Standards: standards/what-you-can-do.md


